LOCAL_PATH := $(call my-dir)

FFMPEG_PATH=$(LOCAL_PATH)/libffmpeg
FFMPEG_INCLUDE=$(FFMPEG_PATH)/include
FFMPEG_LIB=libffmpeg/lib

include $(CLEAR_VARS)
LOCAL_MODULE:= libavcodec
LOCAL_SRC_FILES:= $(FFMPEG_LIB)/libavcodec.a
LOCAL_EXPORT_C_INCLUDES := $(FFMPEG_INCLUDE)
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE:= libavformat
LOCAL_SRC_FILES:= $(FFMPEG_LIB)/libavformat.a
LOCAL_EXPORT_C_INCLUDES := $(FFMPEG_INCLUDE)
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE:= libavdevice
LOCAL_SRC_FILES:= $(FFMPEG_LIB)/libavdevice.a
LOCAL_EXPORT_C_INCLUDES := $(FFMPEG_INCLUDE)
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE:= libavfilter
LOCAL_SRC_FILES:= $(FFMPEG_LIB)/libavfilter.a
LOCAL_EXPORT_C_INCLUDES := $(FFMPEG_INCLUDE)
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE:= libavutil
LOCAL_SRC_FILES:= $(FFMPEG_LIB)/libavutil.a
LOCAL_EXPORT_C_INCLUDES := $(FFMPEG_INCLUDE)
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE:= libpostproc
LOCAL_SRC_FILES:= $(FFMPEG_LIB)/libpostproc.a
LOCAL_EXPORT_C_INCLUDES := $(FFMPEG_INCLUDE)
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE:= libswresample
LOCAL_SRC_FILES:= $(FFMPEG_LIB)/libswresample.a
LOCAL_EXPORT_C_INCLUDES := $(FFMPEG_INCLUDE)
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE:= libswscale
LOCAL_SRC_FILES:= $(FFMPEG_LIB)/libswscale.a
LOCAL_EXPORT_C_INCLUDES := $(FFMPEG_INCLUDE)
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := ffmpeg
LOCAL_SRC_FILES := libffmpeg.c
#LOCAL_C_INCLUDES := $(FFMPEG_INCLUDE)
LOCAL_EXPORT_C_INCLUDES := $(FFMPEG_INCLUDE)
LOCAL_LDLIBS += -lz
LOCAL_STATIC_LIBRARIES := libavcodec libavformat libavdevice libavfilter libavutil libpostproc libswresample libswscale
include $(BUILD_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := demo
LOCAL_SRC_FILES := demo.c
LOCAL_C_INCLUDES := $(FFMPEG_INCLUDE)
LOCAL_LDLIBS := -L$(FFMPEG_LIB)
LOCAL_SHARED_LIBRARIES :=ffmpeg
include $(BUILD_EXECUTABLE)
